title: Hello, world! I'm David Dunn
description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
permalink: ':title/'
baseurl: "" # the subpath of your site, e.g. /blog
url: "daviddunn.tech" # the base hostname & protocol for your site, e.g. http://example.com
site-twitter: #if your site has a twitter account, enter it here

# Author Settings
author: David Dunn # add your name
author-img: david-dunn.jpg # add your photo
about-author: I am a data professional focusing on analysis, visualization, and modeling. Always looking to learn something new. # add description
social-twitter: mrdaviddunn # add your Twitter handle
social-facebook: # add your Facebook handle
social-github: algorhythmic # add your Github handle
social-linkedin: mrdaviddunn # add your Linkedin handle
social-email: davidalexanderdunn@gmail.com # add your Email address

# Disqus
discus-identifier: mr-brown # add your discus identifier

# Tracker
analytics: # Google Analytics

# Build Settings
markdown: kramdown
plugins:
  - jekyll-sitemap
  - jekyll-paginate
  - jemoji

paginate: 8
paginate_path: "/page/:num"

exclude: ["node_modules", "gulpfile.js", "package.json", "yarn.lock"]
